PROP_MIN_MAV_VALID = 0.1
PROP_MAX_MAV_VALID = 2
PROP_UMBRAL_COMPRA = 0.7

GANANCIA_BRUTA_MIN = 300000
GANANCIA_PORCENTUAL_MIN = 0.3
MIN_PERIODS_STD = 4
UMBRAL_STD_MULTI = 2
DIAS_MAX_ESPERA = None
TIEMPO_SLEEP_ENTRE_CARTAS = 1
